# Generated by Django 3.2 on 2021-04-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='Respuesta correcta'),
        ),
    ]
